export const ACCESS_TOKEN_EXPIRY_KEYWORD =
	"ACCESS_TOKEN_EXPIRY_KEYWORD" as const;
export const ACCESS_TOKEN_KEYWORD = "ACCESS_TOKEN_KEYWORD" as const;
export const EMAIL_COOKIE_KEYWORD = "EMAIL_COOKIE_KEYWORD" as const;
export const REFRESH_TOKEN_KEYWORD = "REFRESH_TOKEN_KEYWORD" as const;
export const BEARER_TOKEN_KEYWORD = "BEARER_TOKEN_KEYWORD" as const;
