import { generateUUID } from "@/_utils";
import { Order, Product } from "@/types";

export const mockProducts: Product[] = [
	{
		id: generateUUID(),
		name: "Brain Super Food",
		price: 35000,
		originalPrice: 40000,
		// image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop",
		image: "/images/BrainSuper.png",
		category: "Fruits",
		description:
			"Executive and Cognitive Function | Manage Memory Loss | Mental Wellness",
		quantity: 10,
		inStock: true,
		rating: 4.8,
		reviews: 124,
	},
	{
		id: generateUUID(),
		name: "Gut Brain Superfood",
		price: 30000,
		originalPrice: 35000,
		// image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop",
		image: "/images/GUTBrainSuperfood.png",
		category: "Vegetables",
		description:
			"Improves Gut health | It supports good sleep | Increases organic probiotics | Mental Wellness",
		quantity: 10,
		inStock: true,
		rating: 3.6,
		reviews: 89,
	},
	{
		id: generateUUID(),
		name: "Exotic green smoothie",
		price: 20000,
		originalPrice: 25000,
		// image: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&h=400&fit=crop",
		image: "/images/smoothie-removebg.png",
		category: "Fruits",
		description:
			"Immune Booster | Heart, Liver and Kidney Health | Enhance Digestion",
		quantity: 10,
		inStock: true,
		rating: 3.9,
		reviews: 156,
	},
	{
		id: generateUUID(),
		name: "Ultimate Organic Aphrodisiac (For Men)",
		price: 20000,
		originalPrice: 24000,
		// image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop",
		image: "/images/capsule-removebg.png",
		category: "Grains",
		description:
			"Libido Enhancer, Increased Testosterone, Stress Management, For Erectile Dysfunction, Improved Sperm Quality",
		quantity: 10,
		inStock: true,
		rating: 2.7,
		reviews: 203,
	},
	{
		id: generateUUID(),
		name: "Goron Tula - Fruit & Powder (For Women)",
		price: 10000,
		originalPrice: 12500,
		// image: "https://images.unsplash.com/photo-1582515073490-39981397c445?w=400&h=400&fit=crop",
		image: "/images/gorontula-removebg.png",
		category: "Vegetables",
		description: "Enhances reproductive health and boosts immunity naturally",
		quantity: 0,
		inStock: false,
		rating: 2.5,
		reviews: 78,
	},
	{
		id: generateUUID(),
		name: "Purple Super Food",
		price: 24000,
		originalPrice: 30000,
		// image: "https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400&h=400&fit=crop",
		image: "/images/purple-super-food-preview.png",
		category: "Pantry",
		description:
			"Prevents/Fights Cancer | Reduce Heart Disease Risk | Boost Brain Health | Packed with Antioxidant | Radiant Skin | Pre/Post Workout + Many More",
		quantity: 10,
		inStock: true,
		rating: 2.8,
		reviews: 145,
	},
	{
		id: generateUUID(),
		name: "Dates Powder",
		price: 2500,
		// originalPrice: 25000,
		// image: "https://unsplash.com/photos/a-pile-of-broccoli-sitting-on-top-of-a-white-table-t6DpKVQdLYQ?w=400&h=400&fit=crop",
		image: "/images/dates-powder-preview.png",
		category: "Vegetables",
		description:
			"Promotes Healthy Pregnancy | Supports Eye Health | Boosts Energy | Aids Digestion | Supports Heart Health | Strengthens Bones | Improves Brain Function | Regulates Blood Sugar",
		quantity: 10,
		inStock: true,
		rating: 5,
		reviews: 92,
	},
	{
		id: generateUUID(),
		name: "Tigernuts Powder",
		price: 2000,
		// originalPrice: 25000,
		// image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&h=400&fit=crop",
		image: "/images/tigernuts-powder-preview.png",
		category: "Fruits",
		description:
			"Promotes Healthy Skin | Rich in Fiber | Boosts Energy | Supports Heart Health | Regulates Blood Sugar | Good for Weight Management | Dairy-Free & Nut-Free",
		quantity: 10,
		inStock: true,
		rating: 5,
		reviews: 167,
	},
	{
		id: generateUUID(),
		name: "Brain Super Food",
		price: 35000,
		originalPrice: 40000,
		// image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop",
		image: "/images/BrainSuper.png",
		category: "Fruits",
		description:
			"Executive and Cognitive Function | Manage Memory Loss | Mental Wellness",
		quantity: 10,
		inStock: true,
		rating: 4.8,
		reviews: 124,
	},
	{
		id: generateUUID(),
		name: "Gut Brain Superfood",
		price: 30000,
		originalPrice: 35000,
		// image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop",
		image: "/images/GUTBrainSuperfood.png",
		category: "Vegetables",
		description:
			"Improves Gut health | It supports good sleep | Increases organic probiotics | Mental Wellness",
		quantity: 10,
		inStock: true,
		rating: 3.6,
		reviews: 89,
	},
	{
		id: generateUUID(),
		name: "Exotic green smoothie",
		price: 20000,
		originalPrice: 25000,
		// image: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&h=400&fit=crop",
		image: "/images/smoothie-removebg.png",
		category: "Fruits",
		description:
			"Immune Booster | Heart, Liver and Kidney Health | Enhance Digestion",
		quantity: 10,
		inStock: true,
		rating: 3.9,
		reviews: 156,
	},
	{
		id: generateUUID(),
		name: "Ultimate Organic Aphrodisiac (For Men)",
		price: 20000,
		originalPrice: 24000,
		// image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop",
		image: "/images/capsule-removebg.png",
		category: "Grains",
		description:
			"Libido Enhancer, Increased Testosterone, Stress Management, For Erectile Dysfunction, Improved Sperm Quality",
		quantity: 10,
		inStock: true,
		rating: 2.7,
		reviews: 203,
	},
	{
		id: generateUUID(),
		name: "Goron Tula - Fruit & Powder (For Women)",
		price: 10000,
		originalPrice: 12500,
		// image: "https://images.unsplash.com/photo-1582515073490-39981397c445?w=400&h=400&fit=crop",
		image: "/images/gorontula-removebg.png",
		category: "Vegetables",
		description: "Enhances reproductive health and boosts immunity naturally",
		quantity: 0,
		inStock: false,
		rating: 2.5,
		reviews: 78,
	},
	{
		id: generateUUID(),
		name: "Purple Super Food",
		price: 24000,
		originalPrice: 30000,
		// image: "https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400&h=400&fit=crop",
		image: "/images/purple-super-food-preview.png",
		category: "Pantry",
		description:
			"Prevents/Fights Cancer | Reduce Heart Disease Risk | Boost Brain Health | Packed with Antioxidant | Radiant Skin | Pre/Post Workout + Many More",
		quantity: 10,
		inStock: true,
		rating: 2.8,
		reviews: 145,
	},
	{
		id: generateUUID(),
		name: "Dates Powder",
		price: 2500,
		// originalPrice: 25000,
		// image: "https://unsplash.com/photos/a-pile-of-broccoli-sitting-on-top-of-a-white-table-t6DpKVQdLYQ?w=400&h=400&fit=crop",
		image: "/images/dates-powder-preview.png",
		category: "Vegetables",
		description:
			"Promotes Healthy Pregnancy | Supports Eye Health | Boosts Energy | Aids Digestion | Supports Heart Health | Strengthens Bones | Improves Brain Function | Regulates Blood Sugar",
		quantity: 10,
		inStock: true,
		rating: 5,
		reviews: 92,
	},
	{
		id: generateUUID(),
		name: "Tigernuts Powder",
		price: 2000,
		// originalPrice: 25000,
		// image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&h=400&fit=crop",
		image: "/images/tigernuts-powder-preview.png",
		category: "Fruits",
		description:
			"Promotes Healthy Skin | Rich in Fiber | Boosts Energy | Supports Heart Health | Regulates Blood Sugar | Good for Weight Management | Dairy-Free & Nut-Free",
		quantity: 10,
		inStock: true,
		rating: 5,
		reviews: 167,
	},
	{
		id: generateUUID(),
		name: "Brain Super Food",
		price: 35000,
		originalPrice: 40000,
		// image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop",
		image: "/images/BrainSuper.png",
		category: "Fruits",
		description:
			"Executive and Cognitive Function | Manage Memory Loss | Mental Wellness",
		quantity: 10,
		inStock: true,
		rating: 4.8,
		reviews: 124,
	},
	{
		id: generateUUID(),
		name: "Gut Brain Superfood",
		price: 30000,
		originalPrice: 35000,
		// image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop",
		image: "/images/GUTBrainSuperfood.png",
		category: "Vegetables",
		description:
			"Improves Gut health | It supports good sleep | Increases organic probiotics | Mental Wellness",
		quantity: 10,
		inStock: true,
		rating: 3.6,
		reviews: 89,
	},
	{
		id: generateUUID(),
		name: "Exotic green smoothie",
		price: 20000,
		originalPrice: 25000,
		// image: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&h=400&fit=crop",
		image: "/images/smoothie-removebg.png",
		category: "Fruits",
		description:
			"Immune Booster | Heart, Liver and Kidney Health | Enhance Digestion",
		quantity: 10,
		inStock: true,
		rating: 3.9,
		reviews: 156,
	},
	{
		id: generateUUID(),
		name: "Ultimate Organic Aphrodisiac (For Men)",
		price: 20000,
		originalPrice: 24000,
		// image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop",
		image: "/images/capsule-removebg.png",
		category: "Grains",
		description:
			"Libido Enhancer, Increased Testosterone, Stress Management, For Erectile Dysfunction, Improved Sperm Quality",
		quantity: 10,
		inStock: true,
		rating: 2.7,
		reviews: 203,
	},
	{
		id: generateUUID(),
		name: "Goron Tula - Fruit & Powder (For Women)",
		price: 10000,
		originalPrice: 12500,
		// image: "https://images.unsplash.com/photo-1582515073490-39981397c445?w=400&h=400&fit=crop",
		image: "/images/gorontula-removebg.png",
		category: "Vegetables",
		description: "Enhances reproductive health and boosts immunity naturally",
		quantity: 0,
		inStock: false,
		rating: 2.5,
		reviews: 78,
	},
	{
		id: generateUUID(),
		name: "Purple Super Food",
		price: 24000,
		originalPrice: 30000,
		// image: "https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400&h=400&fit=crop",
		image: "/images/purple-super-food-preview.png",
		category: "Pantry",
		description:
			"Prevents/Fights Cancer | Reduce Heart Disease Risk | Boost Brain Health | Packed with Antioxidant | Radiant Skin | Pre/Post Workout + Many More",
		quantity: 10,
		inStock: true,
		rating: 2.8,
		reviews: 145,
	},
	{
		id: generateUUID(),
		name: "Dates Powder",
		price: 2500,
		// originalPrice: 25000,
		// image: "https://unsplash.com/photos/a-pile-of-broccoli-sitting-on-top-of-a-white-table-t6DpKVQdLYQ?w=400&h=400&fit=crop",
		image: "/images/dates-powder-preview.png",
		category: "Vegetables",
		description:
			"Promotes Healthy Pregnancy | Supports Eye Health | Boosts Energy | Aids Digestion | Supports Heart Health | Strengthens Bones | Improves Brain Function | Regulates Blood Sugar",
		quantity: 10,
		inStock: true,
		rating: 5,
		reviews: 92,
	},
	{
		id: generateUUID(),
		name: "Tigernuts Powder",
		price: 2000,
		// originalPrice: 25000,
		// image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&h=400&fit=crop",
		image: "/images/tigernuts-powder-preview.png",
		category: "Fruits",
		description:
			"Promotes Healthy Skin | Rich in Fiber | Boosts Energy | Supports Heart Health | Regulates Blood Sugar | Good for Weight Management | Dairy-Free & Nut-Free",
		quantity: 10,
		inStock: true,
		rating: 5,
		reviews: 167,
	},
	{
		id: generateUUID(),
		name: "Brain Super Food",
		price: 35000,
		originalPrice: 40000,
		// image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop",
		image: "/images/BrainSuper.png",
		category: "Fruits",
		description:
			"Executive and Cognitive Function | Manage Memory Loss | Mental Wellness",
		quantity: 10,
		inStock: true,
		rating: 4.8,
		reviews: 124,
	},
	{
		id: generateUUID(),
		name: "Gut Brain Superfood",
		price: 30000,
		originalPrice: 35000,
		// image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop",
		image: "/images/GUTBrainSuperfood.png",
		category: "Vegetables",
		description:
			"Improves Gut health | It supports good sleep | Increases organic probiotics | Mental Wellness",
		quantity: 10,
		inStock: true,
		rating: 3.6,
		reviews: 89,
	},
	{
		id: generateUUID(),
		name: "Exotic green smoothie",
		price: 20000,
		originalPrice: 25000,
		// image: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&h=400&fit=crop",
		image: "/images/smoothie-removebg.png",
		category: "Fruits",
		description:
			"Immune Booster | Heart, Liver and Kidney Health | Enhance Digestion",
		quantity: 10,
		inStock: true,
		rating: 3.9,
		reviews: 156,
	},
	{
		id: generateUUID(),
		name: "Ultimate Organic Aphrodisiac (For Men)",
		price: 20000,
		originalPrice: 24000,
		// image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop",
		image: "/images/capsule-removebg.png",
		category: "Grains",
		description:
			"Libido Enhancer, Increased Testosterone, Stress Management, For Erectile Dysfunction, Improved Sperm Quality",
		quantity: 10,
		inStock: true,
		rating: 2.7,
		reviews: 203,
	},
	{
		id: generateUUID(),
		name: "Goron Tula - Fruit & Powder (For Women)",
		price: 10000,
		originalPrice: 12500,
		// image: "https://images.unsplash.com/photo-1582515073490-39981397c445?w=400&h=400&fit=crop",
		image: "/images/gorontula-removebg.png",
		category: "Vegetables",
		description: "Enhances reproductive health and boosts immunity naturally",
		quantity: 0,
		inStock: false,
		rating: 2.5,
		reviews: 78,
	},
	{
		id: generateUUID(),
		name: "Purple Super Food",
		price: 24000,
		originalPrice: 30000,
		// image: "https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400&h=400&fit=crop",
		image: "/images/purple-super-food-preview.png",
		category: "Pantry",
		description:
			"Prevents/Fights Cancer | Reduce Heart Disease Risk | Boost Brain Health | Packed with Antioxidant | Radiant Skin | Pre/Post Workout + Many More",
		quantity: 10,
		inStock: true,
		rating: 2.8,
		reviews: 145,
	},
	{
		id: generateUUID(),
		name: "Dates Powder",
		price: 2500,
		// originalPrice: 25000,
		// image: "https://unsplash.com/photos/a-pile-of-broccoli-sitting-on-top-of-a-white-table-t6DpKVQdLYQ?w=400&h=400&fit=crop",
		image: "/images/dates-powder-preview.png",
		category: "Vegetables",
		description:
			"Promotes Healthy Pregnancy | Supports Eye Health | Boosts Energy | Aids Digestion | Supports Heart Health | Strengthens Bones | Improves Brain Function | Regulates Blood Sugar",
		quantity: 10,
		inStock: true,
		rating: 5,
		reviews: 92,
	},
	{
		id: generateUUID(),
		name: "Tigernuts Powder",
		price: 2000,
		// originalPrice: 25000,
		// image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&h=400&fit=crop",
		image: "/images/tigernuts-powder-preview.png",
		category: "Fruits",
		description:
			"Promotes Healthy Skin | Rich in Fiber | Boosts Energy | Supports Heart Health | Regulates Blood Sugar | Good for Weight Management | Dairy-Free & Nut-Free",
		quantity: 10,
		inStock: true,
		rating: 5,
		reviews: 167,
	},
];

export const mockOrders: Order[] = [
	{
		id: "1001",
		customer: {
			firstName: "John",
			lastName: "Doe",
			email: "john@example.com",
			phone: "+1234567890",
			totalSpent: 90,
			address: {
				street: "123 Main St",
				city: "New York",
				state: "NY",
				zipCode: "10001",
				country: "USA",
			},
			lastOrderDate: "",
			totalOrders: 8,
		},
		shippingAddress: {
			street: "123 Main St",
			city: "New York",
			state: "NY",
			zipCode: "10001",
			country: "USA",
		},
		billingAddress: {
			street: "123 Main St",
			city: "New York",
			state: "NY",
			zipCode: "10001",
			country: "USA",
		},
		items: [
			{
				id: "1",
				name: "Organic Avocados",
				price: 4.99,
				image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop",
				category: "Fruits",
				description: "Fresh, creamy organic avocados",
				inStock: true,
				// organic: true,
				rating: 4.8,
				reviews: 124,
				quantity: 2,
				createdAt: Date.now(),
			},
		],
		subtotal: 9.98,
		shipping: 9.99,
		tax: 1.6,
		total: 21.57,
		status: "pending",
		createdAt: "2024-01-15T10:30:00Z",
	},
	{
		id: "1002",
		customer: {
			firstName: "Jane",
			lastName: "Smith",
			email: "jane@example.com",
			phone: "+1234567891",
			totalSpent: 60,
			address: {
				street: "123 Main St",
				city: "New York",
				state: "NY",
				zipCode: "10001",
				country: "USA",
			},
			lastOrderDate: "",
			totalOrders: 6,
		},
		shippingAddress: {
			street: "456 Oak Ave",
			city: "Los Angeles",
			state: "CA",
			zipCode: "90210",
			country: "USA",
		},
		billingAddress: {
			street: "456 Oak Ave",
			city: "Los Angeles",
			state: "CA",
			zipCode: "90210",
			country: "USA",
		},
		items: [
			{
				id: "3",
				name: "Organic Blueberries",
				price: 8.99,
				image: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&h=400&fit=crop",
				category: "Fruits",
				description: "Sweet and juicy organic blueberries",
				inStock: true,
				// organic: true,
				rating: 4.9,
				reviews: 156,
				quantity: 1,
				createdAt: Date.now(),
			},
		],
		subtotal: 8.99,
		shipping: 9.99,
		tax: 1.44,
		total: 20.42,
		status: "shipped",
		createdAt: "2024-01-14T15:20:00Z",
	},
];
